/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AbortTransferInstruction {
    'abortKind': AbortTransferInstructionAbortKindEnum;
    'transferInstructionCid': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "abortKind",
            "baseName": "abort_kind",
            "type": "AbortTransferInstructionAbortKindEnum",
            "format": ""
        },
        {
            "name": "transferInstructionCid",
            "baseName": "transfer_instruction_cid",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AbortTransferInstruction.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum AbortTransferInstructionAbortKindEnum {
    Withdraw = 'withdraw',
    Reject = 'reject'
}

