/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CreatedEvent } from '../models/CreatedEvent';
import { HttpFile } from '../http/http';

export class AcsResponse {
    /**
    * The same `record_time` as in the request.
    */
    'recordTime': Date;
    /**
    * The same `migration_id` as in the request.
    */
    'migrationId': number;
    /**
    * Up to `page_size` contracts in the ACS. `create_arguments` are always encoded as `compact_json`. 
    */
    'createdEvents': Array<CreatedEvent>;
    /**
    * When requesting the next page of results, pass this as `after` to the `AcsRequest` or `HoldingsStateRequest`. Will be absent when there are no more pages. 
    */
    'nextPageToken'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "recordTime",
            "baseName": "record_time",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "migrationId",
            "baseName": "migration_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "createdEvents",
            "baseName": "created_events",
            "type": "Array<CreatedEvent>",
            "format": ""
        },
        {
            "name": "nextPageToken",
            "baseName": "next_page_token",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return AcsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
