/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AcsRequest {
    /**
    * The migration id for which to return the ACS. 
    */
    'migrationId': number;
    /**
    * The timestamp at which the contract set was active. Currently, needs to be an exact timestamp, i.e., needs to correspond to a timestamp reported by `/v0/state/acs/snapshot-timestamp`. 
    */
    'recordTime': Date;
    /**
    * Pagination token for the next page of results. For this to be valid, this must be the `next_page_token` from a prior request with identical parameters aside from `after` and `page_size`; the response may be invalid otherwise. 
    */
    'after'?: number;
    /**
    * The maximum number of created events returned for this request. 
    */
    'pageSize': number;
    /**
    * Filters the ACS by contracts in which these party IDs are stakeholders. 
    */
    'partyIds'?: Array<string>;
    /**
    * Filters the ACS by contracts with these template IDs, specified as \"PACKAGE_NAME:MODULE_NAME:ENTITY_NAME\". 
    */
    'templates'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "migrationId",
            "baseName": "migration_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "recordTime",
            "baseName": "record_time",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "after",
            "baseName": "after",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "pageSize",
            "baseName": "page_size",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "partyIds",
            "baseName": "party_ids",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "templates",
            "baseName": "templates",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AcsRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
