/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ActualMemberTrafficState {
    /**
    * Total extra traffic consumed by the member on the given synchronizer 
    */
    'totalConsumed': number;
    /**
    * Current extra traffic limit set for the member on the given synchronizer. An extra traffic top-up is complete once total_limit matches total_purchased. 
    */
    'totalLimit': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "totalConsumed",
            "baseName": "total_consumed",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "totalLimit",
            "baseName": "total_limit",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return ActualMemberTrafficState.attributeTypeMap;
    }

    public constructor() {
    }
}
