/**
 * Wallet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ContractWithState } from '../models/ContractWithState';
import { HttpFile } from '../http/http';

export class AmuletPosition {
    'contract': ContractWithState;
    'round': number;
    'accruedHoldingFee': string;
    'effectiveAmount': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "contract",
            "baseName": "contract",
            "type": "ContractWithState",
            "format": ""
        },
        {
            "name": "round",
            "baseName": "round",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "accruedHoldingFee",
            "baseName": "accrued_holding_fee",
            "type": "string",
            "format": ""
        },
        {
            "name": "effectiveAmount",
            "baseName": "effective_amount",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AmuletPosition.attributeTypeMap;
    }

    public constructor() {
    }
}
