/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AmuletAmount {
    /**
    * The party that owns the amulet. 
    */
    'amuletOwner': string;
    /**
    * The amulet amount. 
    */
    'amuletAmount': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "amuletOwner",
            "baseName": "amulet_owner",
            "type": "string",
            "format": ""
        },
        {
            "name": "amuletAmount",
            "baseName": "amulet_amount",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AmuletAmount.attributeTypeMap;
    }

    public constructor() {
    }
}
