/**
 * ANS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AnsEntryResponse {
    'contractId': string;
    'name': string;
    'amount': string;
    'unit': string;
    'expiresAt': string;
    'paymentInterval': string;
    'paymentDuration': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "contractId",
            "baseName": "contractId",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string",
            "format": ""
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "string",
            "format": ""
        },
        {
            "name": "expiresAt",
            "baseName": "expiresAt",
            "type": "string",
            "format": ""
        },
        {
            "name": "paymentInterval",
            "baseName": "paymentInterval",
            "type": "string",
            "format": ""
        },
        {
            "name": "paymentDuration",
            "baseName": "paymentDuration",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AnsEntryResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
