/**
 * Validator API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AnsEntry {
    /**
    * If present, Daml contract ID of template `Splice.Ans:AnsEntry`. If absent, this is a DSO-provided entry for either the DSO or an SV. 
    */
    'contractId'?: string;
    /**
    * Owner party ID of this ANS entry.
    */
    'user': string;
    /**
    * The ANS entry name.
    */
    'name': string;
    /**
    * Either empty, or an http/https URL supplied by the `user`.
    */
    'url': string;
    /**
    * Arbitrary description text supplied by `user`; may be empty.
    */
    'description': string;
    /**
    * Time after which this ANS entry expires; if renewed, it will have a new `contract_id` and `expires_at`. If `null` or absent, does not expire; this is the case only for special entries provided by the DSO. 
    */
    'expiresAt'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "contractId",
            "baseName": "contract_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "expiresAt",
            "baseName": "expires_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return AnsEntry.attributeTypeMap;
    }

    public constructor() {
    }
}
