/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class BalanceChange {
    /**
    * The party for which the balance changes. 
    */
    'party': string;
    /**
    * The change to the total balance introduced by this balance change, normalized to round zero, i.e., a amulet created in round 3 is treated as a amulet created in round 0 with a higher initial amount. 
    */
    'changeToInitialAmountAsOfRoundZero': string;
    /**
    * The change of total holding fees introduced by this balance change. 
    */
    'changeToHoldingFeesRate': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "party",
            "baseName": "party",
            "type": "string",
            "format": ""
        },
        {
            "name": "changeToInitialAmountAsOfRoundZero",
            "baseName": "change_to_initial_amount_as_of_round_zero",
            "type": "string",
            "format": ""
        },
        {
            "name": "changeToHoldingFeesRate",
            "baseName": "change_to_holding_fees_rate",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BalanceChange.attributeTypeMap;
    }

    public constructor() {
    }
}
