/**
 * Wallet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class BuyTrafficRequestCompletedResponse {
    /**
    * The status of the traffic request created:   The request to buy traffic has been created and is waiting for   the wallet automation to pick it up. completed:   The traffic has been purchased.   transaction_id points to the transaction that purchased traffic. failed:   The request to buy traffic has failed permanently and no CC has been transferred. Refer to   failure_reason for details. Use a new tracking_id if you want to retry buying traffic. 
    */
    'status': string;
    /**
    * Id of the transaction that purchased traffic. 
    */
    'transactionId': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "transactionId",
            "baseName": "transaction_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BuyTrafficRequestCompletedResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
