/**
 * Wallet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class BuyTrafficRequestFailedResponse {
    /**
    * The status of the traffic request created:   The request to buy traffic has been created and is waiting for   the wallet automation to pick it up. completed:   The traffic has been purchased.   transaction_id points to the transaction that purchased traffic. failed:   The request to buy traffic has failed permanently and no CC has been transferred. Refer to   failure_reason for details. Use a new tracking_id if you want to retry buying traffic. 
    */
    'status': string;
    /**
    * The reason for the failure of the request to buy traffic. expired:   The wallet automation did not process the request in time. rejected:   The wallet automation rejected the request, e.g., due to insufficient funds or operational reasons. 
    */
    'failureReason': BuyTrafficRequestFailedResponseFailureReasonEnum;
    /**
    * Human readable description of the rejection reason. 
    */
    'rejectionReason'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "failureReason",
            "baseName": "failure_reason",
            "type": "BuyTrafficRequestFailedResponseFailureReasonEnum",
            "format": ""
        },
        {
            "name": "rejectionReason",
            "baseName": "rejection_reason",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BuyTrafficRequestFailedResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum BuyTrafficRequestFailedResponseFailureReasonEnum {
    Expired = 'expired',
    Rejected = 'rejected'
}

