/**
 * Common schemas for Splice API definitions
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Contract } from '../models/Contract';
import { HttpFile } from '../http/http';

export class ContractWithState {
    'contract': Contract;
    'domainId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "contract",
            "baseName": "contract",
            "type": "Contract",
            "format": ""
        },
        {
            "name": "domainId",
            "baseName": "domain_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ContractWithState.attributeTypeMap;
    }

    public constructor() {
    }
}
