/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CreatedEvent {
    'eventType': string;
    /**
    * The ID of this particular event. Equal to the key of this element of the containing `events_by_id` if this is part of a `TreeEvent`. 
    */
    'eventId': string;
    /**
    * The ID of the created contract. 
    */
    'contractId': string;
    /**
    * The template of the created contract. 
    */
    'templateId': string;
    /**
    * The package name of the created contract. 
    */
    'packageName': string;
    /**
    * The arguments that have been used to create the contract, in the form of JSON representation of a Daml record. 
    */
    'createArguments': any;
    /**
    * Ledger effective time of the transaction that created the contract. 
    */
    'createdAt': Date;
    /**
    * Signatories to the contract, in the form of party IDs. 
    */
    'signatories': Array<string>;
    /**
    * Observers to the contract, in the form of party IDs. 
    */
    'observers': Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "eventType",
            "baseName": "event_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "eventId",
            "baseName": "event_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "contractId",
            "baseName": "contract_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "templateId",
            "baseName": "template_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "packageName",
            "baseName": "package_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "createArguments",
            "baseName": "create_arguments",
            "type": "any",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "signatories",
            "baseName": "signatories",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "observers",
            "baseName": "observers",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreatedEvent.attributeTypeMap;
    }

    public constructor() {
    }
}
