/**
 * ANS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CreateAnsEntryRequest {
    /**
    * The name of the ANS entry. It must end with `.unverified.<ans>` where `<ans>` is the ANS acronym chosen by the DSO. 
    */
    'name': string;
    /**
    * A valid URL or an empty string. Use this to link to a website, such as the homepage of an application provided by the owner of this entry. Must not be longer than 255 characters. 
    */
    'url': string;
    /**
    * A human readable description of the ANS entry. May be empty. Must not be longer than 140 characters. 
    */
    'description': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateAnsEntryRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
