/**
 * ANS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* The response contains the contract IDs of the corresponding subscription request. The user must accept the subscription request via their wallet to create the ANS entry. 
*/
export class CreateAnsEntryResponse {
    'entryContextCid': string;
    'subscriptionRequestCid': string;
    /**
    * The name of the ANS entry, as specified in the request. 
    */
    'name': string;
    /**
    * The URL of the ANS entry, as specified in the request. 
    */
    'url': string;
    /**
    * The description of the ANS entry, as specified in the request. 
    */
    'description': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "entryContextCid",
            "baseName": "entryContextCid",
            "type": "string",
            "format": ""
        },
        {
            "name": "subscriptionRequestCid",
            "baseName": "subscriptionRequestCid",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateAnsEntryResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
