/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ScanInfo } from '../models/ScanInfo';
import { HttpFile } from '../http/http';

export class DomainScans {
    'domainId': string;
    /**
    * SV scans for the associated synchronizer ID; there is at most one scan per SV for each synchronizer ID. 
    */
    'scans': Array<ScanInfo>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "domainId",
            "baseName": "domainId",
            "type": "string",
            "format": ""
        },
        {
            "name": "scans",
            "baseName": "scans",
            "type": "Array<ScanInfo>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DomainScans.attributeTypeMap;
    }

    public constructor() {
    }
}
