/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class DsoSequencer {
    /**
    * The synchronizer migration id corresponding to this sequencer. 
    */
    'migrationId': number;
    /**
    * The id of the sequencer.
    */
    'id': string;
    /**
    * The public accessible url of the sequencer.
    */
    'url': string;
    /**
    * The sequencer\'s operating SV name.
    */
    'svName': string;
    /**
    * Any participant should subscribe to this sequencer after this time. 
    */
    'availableAfter': Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "migrationId",
            "baseName": "migrationId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "svName",
            "baseName": "svName",
            "type": "string",
            "format": ""
        },
        {
            "name": "availableAfter",
            "baseName": "availableAfter",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return DsoSequencer.attributeTypeMap;
    }

    public constructor() {
    }
}
