/**
 * Validator API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ExternalPartySubmission {
    'partyId': string;
    /**
    * base64-encoded transaction. The transaction corresponds to the protobuf definition of a `PreparedTransaction` https://github.com/digital-asset/canton/blob/main/community/ledger-api/src/main/protobuf/com/daml/ledger/api/v2/interactive_submission_data.proto#L18 and can be decoded using standard protobuf libraries. 
    */
    'transaction': string;
    /**
    * hex-encoded ed25519 signature of the hash return by the prepare endpoint in the form `${r}${s}`. 
    */
    'signedTxHash': string;
    /**
    * hex-encoded ed25519 public key
    */
    'publicKey': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "partyId",
            "baseName": "party_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "transaction",
            "baseName": "transaction",
            "type": "string",
            "format": ""
        },
        {
            "name": "signedTxHash",
            "baseName": "signed_tx_hash",
            "type": "string",
            "format": ""
        },
        {
            "name": "publicKey",
            "baseName": "public_key",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ExternalPartySubmission.attributeTypeMap;
    }

    public constructor() {
    }
}
