/**
 * Validator API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ExternalPartyBalanceResponse {
    'partyId': string;
    'totalUnlockedCoin': string;
    'totalLockedCoin': string;
    'totalCoinHoldings': string;
    'accumulatedHoldingFeesUnlocked': string;
    'accumulatedHoldingFeesLocked': string;
    'accumulatedHoldingFeesTotal': string;
    'totalAvailableCoin': string;
    'computedAsOfRound': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "partyId",
            "baseName": "party_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "totalUnlockedCoin",
            "baseName": "total_unlocked_coin",
            "type": "string",
            "format": ""
        },
        {
            "name": "totalLockedCoin",
            "baseName": "total_locked_coin",
            "type": "string",
            "format": ""
        },
        {
            "name": "totalCoinHoldings",
            "baseName": "total_coin_holdings",
            "type": "string",
            "format": ""
        },
        {
            "name": "accumulatedHoldingFeesUnlocked",
            "baseName": "accumulated_holding_fees_unlocked",
            "type": "string",
            "format": ""
        },
        {
            "name": "accumulatedHoldingFeesLocked",
            "baseName": "accumulated_holding_fees_locked",
            "type": "string",
            "format": ""
        },
        {
            "name": "accumulatedHoldingFeesTotal",
            "baseName": "accumulated_holding_fees_total",
            "type": "string",
            "format": ""
        },
        {
            "name": "totalAvailableCoin",
            "baseName": "total_available_coin",
            "type": "string",
            "format": ""
        },
        {
            "name": "computedAsOfRound",
            "baseName": "computed_as_of_round",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return ExternalPartyBalanceResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
