/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ForceAcsSnapshotResponse {
    /**
    * The [recent] time for which this ACS snapshot was persisted. 
    */
    'recordTime': Date;
    /**
    * The current migration ID of the Scan.
    */
    'migrationId': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "recordTime",
            "baseName": "record_time",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "migrationId",
            "baseName": "migration_id",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return ForceAcsSnapshotResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
