/**
 * Validator API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TopologyTx } from '../models/TopologyTx';
import { HttpFile } from '../http/http';

export class GenerateExternalPartyTopologyResponse {
    /**
    * The generated party id of the external user. 
    */
    'partyId': string;
    'topologyTxs': Array<TopologyTx>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "partyId",
            "baseName": "party_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "topologyTxs",
            "baseName": "topology_txs",
            "type": "Array<TopologyTx>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GenerateExternalPartyTopologyResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
