/**
 * Validator API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class GenerateExternalPartyTopologyRequest {
    /**
    * The actual party id will be constructed from this hint and a fingerprint of the public key. 
    */
    'partyHint': string;
    /**
    * hex-encoded ed25519 public key
    */
    'publicKey': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "partyHint",
            "baseName": "party_hint",
            "type": "string",
            "format": ""
        },
        {
            "name": "publicKey",
            "baseName": "public_key",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GenerateExternalPartyTopologyRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
