/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SteppedRate } from '../models/SteppedRate';
import { HttpFile } from '../http/http';

export class GetAmuletConfigForRoundResponse {
    'amuletCreateFee': string;
    'holdingFee': string;
    'lockHolderFee': string;
    'transferFee': SteppedRate;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "amuletCreateFee",
            "baseName": "amulet_create_fee",
            "type": "string",
            "format": ""
        },
        {
            "name": "holdingFee",
            "baseName": "holding_fee",
            "type": "string",
            "format": ""
        },
        {
            "name": "lockHolderFee",
            "baseName": "lock_holder_fee",
            "type": "string",
            "format": ""
        },
        {
            "name": "transferFee",
            "baseName": "transfer_fee",
            "type": "SteppedRate",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetAmuletConfigForRoundResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
