/**
 * Validator API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MaybeCachedContractWithState } from '../models/MaybeCachedContractWithState';
import { HttpFile } from '../http/http';

/**
* A contract state update of Daml template `Splice.Ans.AnsRules`. 
*/
export class GetAnsRulesResponse {
    'ansRulesUpdate': MaybeCachedContractWithState;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "ansRulesUpdate",
            "baseName": "ans_rules_update",
            "type": "MaybeCachedContractWithState",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetAnsRulesResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
