/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MaybeCachedContractWithState } from '../models/MaybeCachedContractWithState';
import { HttpFile } from '../http/http';

/**
* Contract of the Daml template `Splice.AmuletRules.AmuletRules`, including the full schedule of `AmuletConfig` changes approved by the DSO. Callers should not assume that `initialValue` is up-to-date, and should instead search `futureValues` for the latest configuration valid as of now. `contract` will be absent if its ID matches the input `cached_amulet_rules_contract_id`. 
*/
export class GetAmuletRulesResponse {
    'amuletRulesUpdate': MaybeCachedContractWithState;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "amuletRulesUpdate",
            "baseName": "amulet_rules_update",
            "type": "MaybeCachedContractWithState",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetAmuletRulesResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
