/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class GetBackfillingStatusResponse {
    /**
    * True if ALL backfilling processes are complete, false otherwise.  Some scan endpoints return error responses if backfilling is not complete (e.g., `/v1/updates`), others return partial results (e.g., `/v0/transactions`). This endpoint is a simple indicator for whether historical information may be incomplete.  To determine the progress of individual backfilling processes, inspect the corresponding metrics. 
    */
    'complete': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "complete",
            "baseName": "complete",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetBackfillingStatusResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
