/**
 * Wallet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BuyTrafficRequestCompletedResponse } from '../models/BuyTrafficRequestCompletedResponse';
import { BuyTrafficRequestCreatedResponse } from '../models/BuyTrafficRequestCreatedResponse';
import { BuyTrafficRequestFailedResponse } from '../models/BuyTrafficRequestFailedResponse';
import { HttpFile } from '../http/http';

/**
 * @type GetBuyTrafficRequestStatusResponse
 * Type
 * @export
 */
export type GetBuyTrafficRequestStatusResponse = BuyTrafficRequestCompletedResponse | BuyTrafficRequestCreatedResponse | BuyTrafficRequestFailedResponse;

/**
* @type GetBuyTrafficRequestStatusResponseClass
* @export
*/
export class GetBuyTrafficRequestStatusResponseClass {
    static readonly discriminator: string | undefined = "status";

    static readonly mapping: {[index: string]: string} | undefined = {
        "completed": "BuyTrafficRequestCompletedResponse",
        "created": "BuyTrafficRequestCreatedResponse",
        "failed": "BuyTrafficRequestFailedResponse",
    };
}


