/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class GetExternalPartyAmuletRulesRequest {
    'cachedExternalPartyAmuletRulesContractId'?: string;
    'cachedExternalPartyAmuletRulesDomainId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "cachedExternalPartyAmuletRulesContractId",
            "baseName": "cached_external_party_amulet_rules_contract_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "cachedExternalPartyAmuletRulesDomainId",
            "baseName": "cached_external_party_amulet_rules_domain_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetExternalPartyAmuletRulesRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
