/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RecordTimeRange } from '../models/RecordTimeRange';
import { HttpFile } from '../http/http';

export class GetMigrationInfoResponse {
    /**
    * The migration id that was active before the given migration id, if any. 
    */
    'previousMigrationId'?: number;
    /**
    * All domains for which there are updates in the given migration id, along with the record time of the newest and oldest update associated with each domain 
    */
    'recordTimeRange': Array<RecordTimeRange>;
    /**
    * True if this scan has all updates for given migration id 
    */
    'complete': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "previousMigrationId",
            "baseName": "previous_migration_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "recordTimeRange",
            "baseName": "record_time_range",
            "type": "Array<RecordTimeRange>",
            "format": ""
        },
        {
            "name": "complete",
            "baseName": "complete",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetMigrationInfoResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
