/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MemberTrafficStatus } from '../models/MemberTrafficStatus';
import { HttpFile } from '../http/http';

export class GetMemberTrafficStatusResponse {
    'trafficStatus': MemberTrafficStatus;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "trafficStatus",
            "baseName": "traffic_status",
            "type": "MemberTrafficStatus",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetMemberTrafficStatusResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
