/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class GetOpenAndIssuingMiningRoundsRequest {
    /**
    * The contract IDs for `open_mining_rounds` in the response the caller knows about. If unsure, an empty array is fine; only a performance penalty is incurred. 
    */
    'cachedOpenMiningRoundContractIds': Array<string>;
    /**
    * The contract IDs for `issuing_mining_rounds` in the response the caller knows about. If unsure, an empty array is fine; only a performance penalty is incurred. 
    */
    'cachedIssuingRoundContractIds': Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "cachedOpenMiningRoundContractIds",
            "baseName": "cached_open_mining_round_contract_ids",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "cachedIssuingRoundContractIds",
            "baseName": "cached_issuing_round_contract_ids",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetOpenAndIssuingMiningRoundsRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
