/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class GetSpliceInstanceNamesResponse {
    /**
    * What to call this Splice network.
    */
    'networkName': string;
    /**
    * URL of an HTML favicon for this Splice network.
    */
    'networkFaviconUrl': string;
    /**
    * What this Splice network calls Amulet.
    */
    'amuletName': string;
    /**
    * The three-letter acronym for Amulet.
    */
    'amuletNameAcronym': string;
    /**
    * What this Splice network calls the Amulet Name Service.
    */
    'nameServiceName': string;
    /**
    * The acronym for `name_service_name`.
    */
    'nameServiceNameAcronym': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "networkName",
            "baseName": "network_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "networkFaviconUrl",
            "baseName": "network_favicon_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "amuletName",
            "baseName": "amulet_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "amuletNameAcronym",
            "baseName": "amulet_name_acronym",
            "type": "string",
            "format": ""
        },
        {
            "name": "nameServiceName",
            "baseName": "name_service_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "nameServiceNameAcronym",
            "baseName": "name_service_name_acronym",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetSpliceInstanceNamesResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
