/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ValidatorReceivedFaucets } from '../models/ValidatorReceivedFaucets';
import { HttpFile } from '../http/http';

export class GetTopValidatorsByValidatorFaucetsResponse {
    /**
    * Up to `limit` validators, sorted greatest number of rounds collected first 
    */
    'validatorsByReceivedFaucets': Array<ValidatorReceivedFaucets>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "validatorsByReceivedFaucets",
            "baseName": "validatorsByReceivedFaucets",
            "type": "Array<ValidatorReceivedFaucets>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetTopValidatorsByValidatorFaucetsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
