/**
 * Wallet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TransferOfferAcceptedResponse } from '../models/TransferOfferAcceptedResponse';
import { TransferOfferCompletedResponse } from '../models/TransferOfferCompletedResponse';
import { TransferOfferCreatedResponse } from '../models/TransferOfferCreatedResponse';
import { TransferOfferFailedResponse } from '../models/TransferOfferFailedResponse';
import { HttpFile } from '../http/http';

/**
 * @type GetTransferOfferStatusResponse
 * Type
 * @export
 */
export type GetTransferOfferStatusResponse = TransferOfferAcceptedResponse | TransferOfferCompletedResponse | TransferOfferCreatedResponse | TransferOfferFailedResponse;

/**
* @type GetTransferOfferStatusResponseClass
* @export
*/
export class GetTransferOfferStatusResponseClass {
    static readonly discriminator: string | undefined = "status";

    static readonly mapping: {[index: string]: string} | undefined = {
        "accepted": "TransferOfferAcceptedResponse",
        "completed": "TransferOfferCompletedResponse",
        "created": "TransferOfferCreatedResponse",
        "failed": "TransferOfferFailedResponse",
    };
}



