/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class GetUpdatesBeforeRequest {
    'migrationId': number;
    'synchronizerId': string;
    /**
    * Only return updates with a record time strictly smaller than this time. 
    */
    'before': Date;
    /**
    * Only return updates with a record time equal to or greater than this time. 
    */
    'atOrAfter'?: Date;
    /**
    * Return at most this many updates. The actual number of updates returned may be smaller. 
    */
    'count': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "migrationId",
            "baseName": "migration_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "synchronizerId",
            "baseName": "synchronizer_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "before",
            "baseName": "before",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "atOrAfter",
            "baseName": "at_or_after",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return GetUpdatesBeforeRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
