/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UpdateHistoryItem } from '../models/UpdateHistoryItem';
import { HttpFile } from '../http/http';

export class GetUpdatesBeforeResponse {
    'transactions': Array<UpdateHistoryItem>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "transactions",
            "baseName": "transactions",
            "type": "Array<UpdateHistoryItem>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetUpdatesBeforeResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
