/**
 * Validator API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class GetValidatorUserInfoResponse {
    /**
    * The daml party id of the validator operator. 
    */
    'partyId': string;
    /**
    * The ledger API user of the validator operator. 
    */
    'userName': string;
    'featured': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "partyId",
            "baseName": "party_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "userName",
            "baseName": "user_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "featured",
            "baseName": "featured",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetValidatorUserInfoResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
