/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class HoldingsSummaryRequest {
    /**
    * The migration id for which to return the summary. 
    */
    'migrationId': number;
    /**
    * The timestamp at which the contract set was active. Currently, needs to be an exact timestamp, i.e., needs to correspond to a timestamp reported by `/v0/state/acs/snapshot-timestamp`. 
    */
    'recordTime': Date;
    /**
    * The owners for which to compute the summary. 
    */
    'ownerPartyIds': Array<string>;
    /**
    * Compute holding fees as of this round. Defaults to the earliest open mining round. 
    */
    'asOfRound'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "migrationId",
            "baseName": "migration_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "recordTime",
            "baseName": "record_time",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "ownerPartyIds",
            "baseName": "owner_party_ids",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "asOfRound",
            "baseName": "as_of_round",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return HoldingsSummaryRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
