/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Aggregate Amulet totals for a particular owner party ID.
*/
export class HoldingsSummary {
    /**
    * Owner party ID of the amulet. Guaranteed to be unique among `summaries`. 
    */
    'partyId': string;
    /**
    * Sum of unlocked amulet at time of reception, not counting holding fees deducted since. 
    */
    'totalUnlockedCoin': string;
    /**
    * Sum of locked amulet at time of original amulet reception, not counting holding fees deducted since. 
    */
    'totalLockedCoin': string;
    /**
    * `total_unlocked_coin` + `total_locked_coin`. 
    */
    'totalCoinHoldings': string;
    /**
    * Sum of holding fees as of `computed_as_of_round` that apply to unlocked amulet. 
    */
    'accumulatedHoldingFeesUnlocked': string;
    /**
    * Sum of holding fees as of `computed_as_of_round` that apply to locked amulet, including fees applied since the amulet\'s creation round. 
    */
    'accumulatedHoldingFeesLocked': string;
    /**
    * Same as `accumulated_holding_fees_unlocked` + `accumulated_holding_fees_locked`. 
    */
    'accumulatedHoldingFeesTotal': string;
    /**
    * Same as `total_unlocked_coin` - `accumulated_holding_fees_unlocked`.
    */
    'totalAvailableCoin': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "partyId",
            "baseName": "party_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "totalUnlockedCoin",
            "baseName": "total_unlocked_coin",
            "type": "string",
            "format": ""
        },
        {
            "name": "totalLockedCoin",
            "baseName": "total_locked_coin",
            "type": "string",
            "format": ""
        },
        {
            "name": "totalCoinHoldings",
            "baseName": "total_coin_holdings",
            "type": "string",
            "format": ""
        },
        {
            "name": "accumulatedHoldingFeesUnlocked",
            "baseName": "accumulated_holding_fees_unlocked",
            "type": "string",
            "format": ""
        },
        {
            "name": "accumulatedHoldingFeesLocked",
            "baseName": "accumulated_holding_fees_locked",
            "type": "string",
            "format": ""
        },
        {
            "name": "accumulatedHoldingFeesTotal",
            "baseName": "accumulated_holding_fees_total",
            "type": "string",
            "format": ""
        },
        {
            "name": "totalAvailableCoin",
            "baseName": "total_available_coin",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return HoldingsSummary.attributeTypeMap;
    }

    public constructor() {
    }
}
