/**
 * Common schemas for Splice API definitions
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class KmsKeyId {
    'type': KmsKeyIdTypeEnum;
    'keyId': string;
    'name'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "KmsKeyIdTypeEnum",
            "format": ""
        },
        {
            "name": "keyId",
            "baseName": "keyId",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return KmsKeyId.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum KmsKeyIdTypeEnum {
    Signing = 'signing',
    Encryption = 'encryption'
}

