/**
 * Wallet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BalanceChangeResponseItem } from '../models/BalanceChangeResponseItem';
import { NotificationResponseItem } from '../models/NotificationResponseItem';
import { TransferResponseItem } from '../models/TransferResponseItem';
import { UnknownResponseItem } from '../models/UnknownResponseItem';
import { HttpFile } from '../http/http';

/**
 * @type ListTransactionsResponseItem
 * Type
 * @export
 */
export type ListTransactionsResponseItem = BalanceChangeResponseItem | NotificationResponseItem | TransferResponseItem | UnknownResponseItem;

/**
* @type ListTransactionsResponseItemClass
* @export
*/
export class ListTransactionsResponseItemClass {
    static readonly discriminator: string | undefined = "transactionType";

    static readonly mapping: {[index: string]: string} | undefined = {
        "balance_change": "BalanceChangeResponseItem",
        "notification": "NotificationResponseItem",
        "transfer": "TransferResponseItem",
        "unknown": "UnknownResponseItem",
    };
}



