/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ListRoundPartyTotalsRequest {
    'startRound': number;
    'endRound': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "startRound",
            "baseName": "start_round",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "endRound",
            "baseName": "end_round",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return ListRoundPartyTotalsRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
