/**
 * Wallet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AmuletPosition } from '../models/AmuletPosition';
import { HttpFile } from '../http/http';

export class ListResponse {
    'amulets': Array<AmuletPosition>;
    'lockedAmulets': Array<AmuletPosition>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "amulets",
            "baseName": "amulets",
            "type": "Array<AmuletPosition>",
            "format": ""
        },
        {
            "name": "lockedAmulets",
            "baseName": "locked_amulets",
            "type": "Array<AmuletPosition>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
