/**
 * ANS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AnsEntryResponse } from '../models/AnsEntryResponse';
import { HttpFile } from '../http/http';

export class ListAnsEntriesResponse {
    'entries': Array<AnsEntryResponse>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "entries",
            "baseName": "entries",
            "type": "Array<AnsEntryResponse>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListAnsEntriesResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
