/**
 * Common schemas for Splice API definitions
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Contract } from '../models/Contract';
import { HttpFile } from '../http/http';

export class ListValidatorLicensesResponse {
    /**
    * Contracts of Daml template `Splice.ValidatorLicense:ValidatorLicense`.
    */
    'validatorLicenses': Array<Contract>;
    /**
    * When requesting the next page of results, pass this as URL query parameter `after`. If absent or `null`, there are no more pages. 
    */
    'nextPageToken'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "validatorLicenses",
            "baseName": "validator_licenses",
            "type": "Array<Contract>",
            "format": ""
        },
        {
            "name": "nextPageToken",
            "baseName": "next_page_token",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return ListValidatorLicensesResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
