/**
 * Common schemas for Splice API definitions
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ListVoteResultsRequest {
    'actionName'?: string;
    'accepted'?: boolean;
    'requester'?: string;
    'effectiveFrom'?: string;
    'effectiveTo'?: string;
    'limit': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "actionName",
            "baseName": "actionName",
            "type": "string",
            "format": ""
        },
        {
            "name": "accepted",
            "baseName": "accepted",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "requester",
            "baseName": "requester",
            "type": "string",
            "format": ""
        },
        {
            "name": "effectiveFrom",
            "baseName": "effectiveFrom",
            "type": "string",
            "format": ""
        },
        {
            "name": "effectiveTo",
            "baseName": "effectiveTo",
            "type": "string",
            "format": ""
        },
        {
            "name": "limit",
            "baseName": "limit",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListVoteResultsRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
