/**
 * Common schemas for Splice API definitions
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Contract } from '../models/Contract';
import { HttpFile } from '../http/http';

export class ListVoteRequestByTrackingCidResponse {
    /**
    * Contracts of Daml template `Splice.DsoRules:VoteRequest` that match `vote_request_contract_ids` in the request. 
    */
    'voteRequests': Array<Contract>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "voteRequests",
            "baseName": "vote_requests",
            "type": "Array<Contract>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListVoteRequestByTrackingCidResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
