/**
 * Validator API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Contract } from '../models/Contract';
import { HttpFile } from '../http/http';

/**
* If defined, a contract of Daml template `Splice.Amulet.FeaturedAppRight`. 
*/
export class LookupFeaturedAppRightResponse {
    'featuredAppRight'?: Contract;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "featuredAppRight",
            "baseName": "featured_app_right",
            "type": "Contract",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LookupFeaturedAppRightResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
