/**
 * Validator API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TransferCommandContractWithStatus } from '../models/TransferCommandContractWithStatus';
import { HttpFile } from '../http/http';

export class LookupTransferCommandStatusResponse {
    'transferCommandsByContractId': { [key: string]: TransferCommandContractWithStatus; };

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "transferCommandsByContractId",
            "baseName": "transfer_commands_by_contract_id",
            "type": "{ [key: string]: TransferCommandContractWithStatus; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LookupTransferCommandStatusResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
