/**
 * Common schemas for Splice API definitions
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KeyPair } from '../models/KeyPair';
import { KmsKeyId } from '../models/KmsKeyId';
import { HttpFile } from '../http/http';

/**
 * @type NodeKey
 * Type
 * @export
 */
export type NodeKey = KeyPair | KmsKeyId;

/**
* @type NodeKeyClass
* @export
*/
export class NodeKeyClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

