/**
 * Common schemas for Splice API definitions
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NodeKey } from '../models/NodeKey';
import { HttpFile } from '../http/http';

export class NodeIdentitiesDump {
    'id': string;
    'keys': Array<NodeKey>;
    /**
    * base64 encoded string of authorized store snapshot 
    */
    'authorizedStoreSnapshot': string;
    'version'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "keys",
            "baseName": "keys",
            "type": "Array<NodeKey>",
            "format": ""
        },
        {
            "name": "authorizedStoreSnapshot",
            "baseName": "authorizedStoreSnapshot",
            "type": "string",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NodeIdentitiesDump.attributeTypeMap;
    }

    public constructor() {
    }
}
