/**
 * Common schemas for Splice API definitions
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FailureStatusResponse } from '../models/FailureStatusResponse';
import { NotInitializedStatusResponse } from '../models/NotInitializedStatusResponse';
import { SuccessStatusResponse } from '../models/SuccessStatusResponse';
import { HttpFile } from '../http/http';

/**
 * @type NodeStatus
 * Type
 * @export
 */
export type NodeStatus = FailureStatusResponse | NotInitializedStatusResponse | SuccessStatusResponse;

/**
* @type NodeStatusClass
* @export
*/
export class NodeStatusClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}


