/**
 * Common schemas for Splice API definitions
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NotInitialized } from '../models/NotInitialized';
import { HttpFile } from '../http/http';

export class NotInitializedStatusResponse {
    'notInitialized': NotInitialized;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "notInitialized",
            "baseName": "not_initialized",
            "type": "NotInitialized",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NotInitializedStatusResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
