/**
 * Validator API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class OnboardUserRequest {
    'name': string;
    /**
    * The party id of the user to onboard. This is optional and if not provided a fresh party id will be generated by the backend. 
    */
    'partyId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "partyId",
            "baseName": "party_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OnboardUserRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
