/**
 * Common schemas for Splice API definitions
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ParticipantUserRight {
    'kind': ParticipantUserRightKindEnum;
    'party'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "kind",
            "baseName": "kind",
            "type": "ParticipantUserRightKindEnum",
            "format": ""
        },
        {
            "name": "party",
            "baseName": "party",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ParticipantUserRight.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum ParticipantUserRightKindEnum {
    ParticipantAdmin = 'participantAdmin',
    CanActAs = 'canActAs',
    CanReadAs = 'canReadAs',
    IdentityProviderAdmin = 'identityProviderAdmin',
    CanReadAsAnyParty = 'canReadAsAnyParty'
}

