/**
 * Common schemas for Splice API definitions
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ParticipantIdentityProvider {
    'id': string;
    'isDeactivated': boolean;
    'jwksUrl': string;
    'issuer': string;
    'audience': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "isDeactivated",
            "baseName": "isDeactivated",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "jwksUrl",
            "baseName": "jwksUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "issuer",
            "baseName": "issuer",
            "type": "string",
            "format": ""
        },
        {
            "name": "audience",
            "baseName": "audience",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ParticipantIdentityProvider.attributeTypeMap;
    }

    public constructor() {
    }
}
