/**
 * Validator API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PrepareAcceptExternalPartySetupProposalRequest {
    'contractId': string;
    'userPartyId': string;
    /**
    * When true, the response will contain additional details on how the transaction was encoded and hashed. This can be useful for troubleshooting of hash mismatches. Should only be used for debugging. 
    */
    'verboseHashing'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "contractId",
            "baseName": "contract_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "userPartyId",
            "baseName": "user_party_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "verboseHashing",
            "baseName": "verbose_hashing",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PrepareAcceptExternalPartySetupProposalRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
