/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ReceiverAmount {
    /**
    * The receiver who will own the created output amulet. 
    */
    'party': string;
    /**
    * The amount of amulet to receive, before deducting receiver\'s part of the fees. 
    */
    'amount': string;
    /**
    * Total fees paid by the receiver, based on receiver_fee_ratio on outputs 
    */
    'receiverFee': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "party",
            "baseName": "party",
            "type": "string",
            "format": ""
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string",
            "format": ""
        },
        {
            "name": "receiverFee",
            "baseName": "receiver_fee",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ReceiverAmount.attributeTypeMap;
    }

    public constructor() {
    }
}
