/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class RecordTimeRange {
    'synchronizerId': string;
    'min': Date;
    'max': Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "synchronizerId",
            "baseName": "synchronizer_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "min",
            "baseName": "min",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "max",
            "baseName": "max",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return RecordTimeRange.attributeTypeMap;
    }

    public constructor() {
    }
}
