/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class RoundPartyTotals {
    'closedRound': number;
    'party': string;
    'appRewards': string;
    'validatorRewards': string;
    'trafficPurchased': number;
    'trafficPurchasedCcSpent': string;
    'trafficNumPurchases': number;
    'cumulativeAppRewards': string;
    'cumulativeValidatorRewards': string;
    'cumulativeChangeToInitialAmountAsOfRoundZero': string;
    'cumulativeChangeToHoldingFeesRate': string;
    'cumulativeTrafficPurchased': number;
    'cumulativeTrafficPurchasedCcSpent': string;
    'cumulativeTrafficNumPurchases': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "closedRound",
            "baseName": "closed_round",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "party",
            "baseName": "party",
            "type": "string",
            "format": ""
        },
        {
            "name": "appRewards",
            "baseName": "app_rewards",
            "type": "string",
            "format": ""
        },
        {
            "name": "validatorRewards",
            "baseName": "validator_rewards",
            "type": "string",
            "format": ""
        },
        {
            "name": "trafficPurchased",
            "baseName": "traffic_purchased",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "trafficPurchasedCcSpent",
            "baseName": "traffic_purchased_cc_spent",
            "type": "string",
            "format": ""
        },
        {
            "name": "trafficNumPurchases",
            "baseName": "traffic_num_purchases",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "cumulativeAppRewards",
            "baseName": "cumulative_app_rewards",
            "type": "string",
            "format": ""
        },
        {
            "name": "cumulativeValidatorRewards",
            "baseName": "cumulative_validator_rewards",
            "type": "string",
            "format": ""
        },
        {
            "name": "cumulativeChangeToInitialAmountAsOfRoundZero",
            "baseName": "cumulative_change_to_initial_amount_as_of_round_zero",
            "type": "string",
            "format": ""
        },
        {
            "name": "cumulativeChangeToHoldingFeesRate",
            "baseName": "cumulative_change_to_holding_fees_rate",
            "type": "string",
            "format": ""
        },
        {
            "name": "cumulativeTrafficPurchased",
            "baseName": "cumulative_traffic_purchased",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "cumulativeTrafficPurchasedCcSpent",
            "baseName": "cumulative_traffic_purchased_cc_spent",
            "type": "string",
            "format": ""
        },
        {
            "name": "cumulativeTrafficNumPurchases",
            "baseName": "cumulative_traffic_num_purchases",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return RoundPartyTotals.attributeTypeMap;
    }

    public constructor() {
    }
}
