/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class RoundTotals {
    'closedRound': number;
    'closedRoundEffectiveAt': Date;
    'appRewards': string;
    'validatorRewards': string;
    'changeToInitialAmountAsOfRoundZero': string;
    'changeToHoldingFeesRate': string;
    'cumulativeAppRewards': string;
    'cumulativeValidatorRewards': string;
    'cumulativeChangeToInitialAmountAsOfRoundZero': string;
    'cumulativeChangeToHoldingFeesRate': string;
    'totalAmuletBalance': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "closedRound",
            "baseName": "closed_round",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "closedRoundEffectiveAt",
            "baseName": "closed_round_effective_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "appRewards",
            "baseName": "app_rewards",
            "type": "string",
            "format": ""
        },
        {
            "name": "validatorRewards",
            "baseName": "validator_rewards",
            "type": "string",
            "format": ""
        },
        {
            "name": "changeToInitialAmountAsOfRoundZero",
            "baseName": "change_to_initial_amount_as_of_round_zero",
            "type": "string",
            "format": ""
        },
        {
            "name": "changeToHoldingFeesRate",
            "baseName": "change_to_holding_fees_rate",
            "type": "string",
            "format": ""
        },
        {
            "name": "cumulativeAppRewards",
            "baseName": "cumulative_app_rewards",
            "type": "string",
            "format": ""
        },
        {
            "name": "cumulativeValidatorRewards",
            "baseName": "cumulative_validator_rewards",
            "type": "string",
            "format": ""
        },
        {
            "name": "cumulativeChangeToInitialAmountAsOfRoundZero",
            "baseName": "cumulative_change_to_initial_amount_as_of_round_zero",
            "type": "string",
            "format": ""
        },
        {
            "name": "cumulativeChangeToHoldingFeesRate",
            "baseName": "cumulative_change_to_holding_fees_rate",
            "type": "string",
            "format": ""
        },
        {
            "name": "totalAmuletBalance",
            "baseName": "total_amulet_balance",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RoundTotals.attributeTypeMap;
    }

    public constructor() {
    }
}
