/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ScanInfo {
    /**
    * The public accessible url of the scan.
    */
    'publicUrl': string;
    /**
    * The sequencer\'s operating SV name.
    */
    'svName': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "publicUrl",
            "baseName": "publicUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "svName",
            "baseName": "svName",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ScanInfo.attributeTypeMap;
    }

    public constructor() {
    }
}
