/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SenderAmount {
    /**
    * The sender who has transferred amulet. 
    */
    'party': string;
    /**
    * Total amount of amulet input into this transfer, before deducting holding fees. 
    */
    'inputAmuletAmount'?: string;
    /**
    * Total amount of app rewards input into this transfer. 
    */
    'inputAppRewardAmount'?: string;
    /**
    * Total amount of validator rewards input into this transfer. 
    */
    'inputValidatorRewardAmount'?: string;
    /**
    * Total amount of sv rewards input into this transfer. 
    */
    'inputSvRewardAmount'?: string;
    /**
    * Total amount of validator faucet coupon issuance input into this transfer. 
    */
    'inputValidatorFaucetAmount'?: string;
    /**
    * Fee charged for returning change to the sender, which is the smaller of the left-over balance after paying for all outputs or one amulet create fee. 
    */
    'senderChangeFee': string;
    /**
    * The final amount of amulet returned to the sender after paying for all outputs and fees. 
    */
    'senderChangeAmount': string;
    /**
    * Total fees paid by the sender, based on receiver\'s receiver_fee_ratio on outputs 
    */
    'senderFee': string;
    /**
    * Holding fees paid by the sender on their input amulets. 
    */
    'holdingFees': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "party",
            "baseName": "party",
            "type": "string",
            "format": ""
        },
        {
            "name": "inputAmuletAmount",
            "baseName": "input_amulet_amount",
            "type": "string",
            "format": ""
        },
        {
            "name": "inputAppRewardAmount",
            "baseName": "input_app_reward_amount",
            "type": "string",
            "format": ""
        },
        {
            "name": "inputValidatorRewardAmount",
            "baseName": "input_validator_reward_amount",
            "type": "string",
            "format": ""
        },
        {
            "name": "inputSvRewardAmount",
            "baseName": "input_sv_reward_amount",
            "type": "string",
            "format": ""
        },
        {
            "name": "inputValidatorFaucetAmount",
            "baseName": "input_validator_faucet_amount",
            "type": "string",
            "format": ""
        },
        {
            "name": "senderChangeFee",
            "baseName": "sender_change_fee",
            "type": "string",
            "format": ""
        },
        {
            "name": "senderChangeAmount",
            "baseName": "sender_change_amount",
            "type": "string",
            "format": ""
        },
        {
            "name": "senderFee",
            "baseName": "sender_fee",
            "type": "string",
            "format": ""
        },
        {
            "name": "holdingFees",
            "baseName": "holding_fees",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SenderAmount.attributeTypeMap;
    }

    public constructor() {
    }
}
