/**
 * Validator API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SequencerAliasToConnections } from '../models/SequencerAliasToConnections';
import { SequencerSubmissionRequestAmplification } from '../models/SequencerSubmissionRequestAmplification';
import { HttpFile } from '../http/http';

export class SequencerConnections {
    'connections': Array<SequencerAliasToConnections>;
    'sequencerTrustThreshold': number;
    'submissionRequestAmplification': SequencerSubmissionRequestAmplification;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "connections",
            "baseName": "connections",
            "type": "Array<SequencerAliasToConnections>",
            "format": ""
        },
        {
            "name": "sequencerTrustThreshold",
            "baseName": "sequencer_trust_threshold",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "submissionRequestAmplification",
            "baseName": "submission_request_amplification",
            "type": "SequencerSubmissionRequestAmplification",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SequencerConnections.attributeTypeMap;
    }

    public constructor() {
    }
}
