/**
 * Validator API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SequencerAliasToConnections {
    'sequencerAlias': string;
    'endpoints': Array<string>;
    'transportSecurity': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "sequencerAlias",
            "baseName": "sequencer_alias",
            "type": "string",
            "format": ""
        },
        {
            "name": "endpoints",
            "baseName": "endpoints",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "transportSecurity",
            "baseName": "transport_security",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SequencerAliasToConnections.attributeTypeMap;
    }

    public constructor() {
    }
}
