/**
 * Validator API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SignedTopologyTx {
    /**
    * base64 encoded topology transaction, this should be identical to the topology transaction received from the /v0/external-party-topology/generate endpoint. 
    */
    'topologyTx': string;
    /**
    * hex-encoded ed25519 signature of the hash return by the generate endpoint in the form `${r}${s}`. 
    */
    'signedHash': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "topologyTx",
            "baseName": "topology_tx",
            "type": "string",
            "format": ""
        },
        {
            "name": "signedHash",
            "baseName": "signed_hash",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SignedTopologyTx.attributeTypeMap;
    }

    public constructor() {
    }
}
