/**
 * Wallet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SubscriptionIdleState } from '../models/SubscriptionIdleState';
import { SubscriptionPaymentState } from '../models/SubscriptionPaymentState';
import { HttpFile } from '../http/http';

/**
 * @type SubscriptionState
 * Type
 * @export
 */
export type SubscriptionState = SubscriptionIdleState | SubscriptionPaymentState;

/**
* @type SubscriptionStateClass
* @export
*/
export class SubscriptionStateClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

