/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SynchronizerBftSequencer {
    /**
    * The synchronizer migration id corresponding to this sequencer. 
    */
    'migrationId': number;
    /**
    * The id of the sequencer.
    */
    'id': string;
    /**
    * The public accessible P2P url of the sequencer, use for inter sequencer communication.
    */
    'p2pUrl': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "migrationId",
            "baseName": "migrationId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "p2pUrl",
            "baseName": "p2pUrl",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SynchronizerBftSequencer.attributeTypeMap;
    }

    public constructor() {
    }
}
