/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SynchronizerBootstrappingTransactions {
    'domainParameters': string;
    'sequencerDomainState': string;
    'mediatorDomainState': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "domainParameters",
            "baseName": "domain_parameters",
            "type": "string",
            "format": ""
        },
        {
            "name": "sequencerDomainState",
            "baseName": "sequencer_domain_state",
            "type": "string",
            "format": ""
        },
        {
            "name": "mediatorDomainState",
            "baseName": "mediator_domain_state",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SynchronizerBootstrappingTransactions.attributeTypeMap;
    }

    public constructor() {
    }
}
