/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SynchronizerIdentities {
    'sequencerId': string;
    'sequencerIdentityTransactions': Array<string>;
    'mediatorId': string;
    'mediatorIdentityTransactions': Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "sequencerId",
            "baseName": "sequencer_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "sequencerIdentityTransactions",
            "baseName": "sequencer_identity_transactions",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "mediatorId",
            "baseName": "mediator_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "mediatorIdentityTransactions",
            "baseName": "mediator_identity_transactions",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SynchronizerIdentities.attributeTypeMap;
    }

    public constructor() {
    }
}
