/**
 * Wallet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PartyAndAmount } from '../models/PartyAndAmount';
import { TransactionSubtype } from '../models/TransactionSubtype';
import { HttpFile } from '../http/http';

export class TransferResponseItem {
    'transactionType': string;
    'transactionSubtype': TransactionSubtype;
    'eventId': string;
    'date': Date;
    'provider': string;
    'sender': PartyAndAmount;
    'receivers': Array<PartyAndAmount>;
    'holdingFees': string;
    'amuletPrice': string;
    'appRewardsUsed': string;
    'validatorRewardsUsed': string;
    'svRewardsUsed': string;
    'transferInstructionReceiver'?: string;
    'transferInstructionAmount'?: string;
    'transferInstructionCid'?: string;
    'description'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "transactionType",
            "baseName": "transaction_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "transactionSubtype",
            "baseName": "transaction_subtype",
            "type": "TransactionSubtype",
            "format": ""
        },
        {
            "name": "eventId",
            "baseName": "event_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "provider",
            "baseName": "provider",
            "type": "string",
            "format": ""
        },
        {
            "name": "sender",
            "baseName": "sender",
            "type": "PartyAndAmount",
            "format": ""
        },
        {
            "name": "receivers",
            "baseName": "receivers",
            "type": "Array<PartyAndAmount>",
            "format": ""
        },
        {
            "name": "holdingFees",
            "baseName": "holding_fees",
            "type": "string",
            "format": ""
        },
        {
            "name": "amuletPrice",
            "baseName": "amulet_price",
            "type": "string",
            "format": ""
        },
        {
            "name": "appRewardsUsed",
            "baseName": "app_rewards_used",
            "type": "string",
            "format": ""
        },
        {
            "name": "validatorRewardsUsed",
            "baseName": "validator_rewards_used",
            "type": "string",
            "format": ""
        },
        {
            "name": "svRewardsUsed",
            "baseName": "sv_rewards_used",
            "type": "string",
            "format": ""
        },
        {
            "name": "transferInstructionReceiver",
            "baseName": "transfer_instruction_receiver",
            "type": "string",
            "format": ""
        },
        {
            "name": "transferInstructionAmount",
            "baseName": "transfer_instruction_amount",
            "type": "string",
            "format": ""
        },
        {
            "name": "transferInstructionCid",
            "baseName": "transfer_instruction_cid",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TransferResponseItem.attributeTypeMap;
    }

    public constructor() {
    }
}
