/**
 * Validator API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class TransferCommandFailedResponse {
    /**
    * The status of the transfer command. created:   The transfer command has been created and is waiting for automation to complete it. sent:   The transfer command has been completed and the transfer to the receiver has finished. failed:   The transfer command has failed permanently and nothing has been transferred. Refer to   failure_reason for details. A new transfer command can be created. 
    */
    'status': string;
    /**
    * The reason for the failure of the TransferCommand. failed:   Completing the transfer failed, check the reason for details. withdrawn:   The sender has withdrawn the TransferCommand before it could be completed. expired:   The expiry time on the TransferCommand was reached before it could be completed. 
    */
    'failureKind': TransferCommandFailedResponseFailureKindEnum;
    /**
    * Human readable description of the failure 
    */
    'reason': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "failureKind",
            "baseName": "failure_kind",
            "type": "TransferCommandFailedResponseFailureKindEnum",
            "format": ""
        },
        {
            "name": "reason",
            "baseName": "reason",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TransferCommandFailedResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum TransferCommandFailedResponseFailureKindEnum {
    Failed = 'failed',
    Expired = 'expired',
    Withdrawn = 'withdrawn'
}

