/**
 * Wallet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TransferInstructionCompleted } from '../models/TransferInstructionCompleted';
import { TransferInstructionFailed } from '../models/TransferInstructionFailed';
import { TransferInstructionPending } from '../models/TransferInstructionPending';
import { HttpFile } from '../http/http';

/**
 * @type TransferInstructionResultOutput
 * Type
 * @export
 */
export type TransferInstructionResultOutput = TransferInstructionCompleted | TransferInstructionFailed | TransferInstructionPending;

/**
* @type TransferInstructionResultOutputClass
* @export
*/
export class TransferInstructionResultOutputClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}


