/**
 * Validator API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TransferCommandCreatedResponse } from '../models/TransferCommandCreatedResponse';
import { TransferCommandFailedResponse } from '../models/TransferCommandFailedResponse';
import { TransferCommandSentResponse } from '../models/TransferCommandSentResponse';
import { HttpFile } from '../http/http';

/**
 * @type TransferCommandContractStatus
 * Type
 * @export
 */
export type TransferCommandContractStatus = TransferCommandCreatedResponse | TransferCommandFailedResponse | TransferCommandSentResponse;

/**
* @type TransferCommandContractStatusClass
* @export
*/
export class TransferCommandContractStatusClass {
    static readonly discriminator: string | undefined = "status";

    static readonly mapping: {[index: string]: string} | undefined = {
        "created": "TransferCommandCreatedResponse",
        "failed": "TransferCommandFailedResponse",
        "sent": "TransferCommandSentResponse",
    };
}


