/**
 * Wallet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class TransferOfferCompletedResponse {
    /**
    * The status of the transfer offer. created:   The offer has been created and is waiting for the receiver to accept it.   contract_id points to the contract_id of the offer and transaction_id to the transaction that created it. accepted:   The offer has been accepted by the receiver and is waiting for the wallet automation   to complete it by delivering the offered Amulet.   contract_id points to the contract id of the accepted offer and transaction_id to the transaction that accepted it completed:   The transfer has been completed and the CC amount has been transferred to the receiver.   contract_id points to the contract id of the created amulet for the receiver and   transaction_id to the transaction of the transfer. failed:   The transfer has failed permanently and no CC has been transferred. Refer to   failure_reason for details. A new transfer offer can be created with a different tracking_id. 
    */
    'status': string;
    /**
    * Id of the transaction of the transfer 
    */
    'transactionId': string;
    /**
    * Contract id of the created amulet for the receiver 
    */
    'contractId': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "transactionId",
            "baseName": "transaction_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "contractId",
            "baseName": "contract_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TransferOfferCompletedResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
