/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BalanceChange } from '../models/BalanceChange';
import { ReceiverAmount } from '../models/ReceiverAmount';
import { SenderAmount } from '../models/SenderAmount';
import { HttpFile } from '../http/http';

/**
* A transfer between one sender and possibly many receivers, provided by an application provider. 
*/
export class Transfer {
    /**
    * The application provider. 
    */
    'provider': string;
    'sender': SenderAmount;
    /**
    * The amounts and fees per receiver. 
    */
    'receivers': Array<ReceiverAmount>;
    /**
    * Normalized balance changes per party caused by this transfer. 
    */
    'balanceChanges': Array<BalanceChange>;
    'description'?: string;
    'transferInstructionReceiver'?: string;
    'transferInstructionAmount'?: string;
    'transferInstructionCid'?: string;
    'transferKind'?: TransferTransferKindEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "provider",
            "baseName": "provider",
            "type": "string",
            "format": ""
        },
        {
            "name": "sender",
            "baseName": "sender",
            "type": "SenderAmount",
            "format": ""
        },
        {
            "name": "receivers",
            "baseName": "receivers",
            "type": "Array<ReceiverAmount>",
            "format": ""
        },
        {
            "name": "balanceChanges",
            "baseName": "balance_changes",
            "type": "Array<BalanceChange>",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "transferInstructionReceiver",
            "baseName": "transferInstructionReceiver",
            "type": "string",
            "format": ""
        },
        {
            "name": "transferInstructionAmount",
            "baseName": "transferInstructionAmount",
            "type": "string",
            "format": ""
        },
        {
            "name": "transferInstructionCid",
            "baseName": "transferInstructionCid",
            "type": "string",
            "format": ""
        },
        {
            "name": "transferKind",
            "baseName": "transfer_kind",
            "type": "TransferTransferKindEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Transfer.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum TransferTransferKindEnum {
    CreateTransferInstruction = 'create_transfer_instruction',
    TransferInstructionAccept = 'transfer_instruction_accept',
    PreapprovalSend = 'preapproval_send'
}

