/**
 * Wallet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class TransactionSubtype {
    'templateId': string;
    'choice': string;
    'amuletOperation'?: string;
    'interfaceId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "templateId",
            "baseName": "template_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "choice",
            "baseName": "choice",
            "type": "string",
            "format": ""
        },
        {
            "name": "amuletOperation",
            "baseName": "amulet_operation",
            "type": "string",
            "format": ""
        },
        {
            "name": "interfaceId",
            "baseName": "interface_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TransactionSubtype.attributeTypeMap;
    }

    public constructor() {
    }
}
