/**
 * Wallet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TransferInstructionResultOutput } from '../models/TransferInstructionResultOutput';
import { HttpFile } from '../http/http';

export class TransferInstructionResultResponse {
    'output': TransferInstructionResultOutput;
    'senderChangeCids': Array<string>;
    'meta': { [key: string]: string; };

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "output",
            "baseName": "output",
            "type": "TransferInstructionResultOutput",
            "format": ""
        },
        {
            "name": "senderChangeCids",
            "baseName": "sender_change_cids",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "meta",
            "baseName": "meta",
            "type": "{ [key: string]: string; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TransferInstructionResultResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
