/**
 * Validator API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Contract } from '../models/Contract';
import { TransferCommandContractStatus } from '../models/TransferCommandContractStatus';
import { HttpFile } from '../http/http';

/**
* A contract of Daml template `Splice.ExternalPartyAmuletRules:TransferCommand`, and its status determined by the latest transactions. 
*/
export class TransferCommandContractWithStatus {
    'contract': Contract;
    'status': TransferCommandContractStatus;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "contract",
            "baseName": "contract",
            "type": "Contract",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "TransferCommandContractStatus",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TransferCommandContractWithStatus.attributeTypeMap;
    }

    public constructor() {
    }
}
