/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CreatedEvent } from '../models/CreatedEvent';
import { ExercisedEvent } from '../models/ExercisedEvent';
import { HttpFile } from '../http/http';

/**
* Either a creation or an exercise of a contract. 
*/
/**
 * @type TreeEvent
 * Type
 * @export
 */
export type TreeEvent = CreatedEvent | ExercisedEvent;

/**
* @type TreeEventClass
    * Either a creation or an exercise of a contract. 
* @export
*/
export class TreeEventClass {
    static readonly discriminator: string | undefined = "eventType";

    static readonly mapping: {[index: string]: string} | undefined = {
        "created_event": "CreatedEvent",
        "exercised_event": "ExercisedEvent",
    };
}

