/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DamlValueEncoding } from '../models/DamlValueEncoding';
import { UpdateHistoryRequestAfter } from '../models/UpdateHistoryRequestAfter';
import { HttpFile } from '../http/http';

export class UpdateHistoryRequestV1 {
    'after'?: UpdateHistoryRequestAfter;
    /**
    * The maximum number of transactions returned for this request. 
    */
    'pageSize': number;
    'damlValueEncoding'?: DamlValueEncoding;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "after",
            "baseName": "after",
            "type": "UpdateHistoryRequestAfter",
            "format": ""
        },
        {
            "name": "pageSize",
            "baseName": "page_size",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "damlValueEncoding",
            "baseName": "daml_value_encoding",
            "type": "DamlValueEncoding",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdateHistoryRequestV1.attributeTypeMap;
    }

    public constructor() {
    }
}


