/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UpdateHistoryRequestAfter {
    /**
    * The migration id from which to start returning transactions. This is inclusive. 
    */
    'afterMigrationId': number;
    /**
    * The record time to start returning transactions from. This only affects transactions with the same migration id as after_migration_id. Higher migration ids are always considered to be later. 
    */
    'afterRecordTime': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "afterMigrationId",
            "baseName": "after_migration_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "afterRecordTime",
            "baseName": "after_record_time",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdateHistoryRequestAfter.attributeTypeMap;
    }

    public constructor() {
    }
}
