/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UpdateHistoryRequestAfter } from '../models/UpdateHistoryRequestAfter';
import { HttpFile } from '../http/http';

export class UpdateHistoryRequest {
    'after'?: UpdateHistoryRequestAfter;
    /**
    * The maximum number of transactions returned for this request. 
    */
    'pageSize': number;
    /**
    * Whether contract payload should be encoded into json using a lossless, but much harder to process, encoding. This is mostly used for backend calls, and is not recommended for external users. Optional and defaults to false. 
    */
    'lossless'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "after",
            "baseName": "after",
            "type": "UpdateHistoryRequestAfter",
            "format": ""
        },
        {
            "name": "pageSize",
            "baseName": "page_size",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "lossless",
            "baseName": "lossless",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdateHistoryRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
