/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UpdateHistoryUnassignment {
    /**
    * The party who submitted this reassignment 
    */
    'submitter': string;
    /**
    * The id of the synchronizer from which the contract was reassigned 
    */
    'sourceSynchronizer': string;
    /**
    * The migration id of the synchronizer from which the contract was reassigned 
    */
    'migrationId': number;
    /**
    * The id of the synchronizer to which the contract was reassigned 
    */
    'targetSynchronizer': string;
    /**
    * The id of the unassign event, to later be correlated to an assign event 
    */
    'unassignId': string;
    /**
    * Each corresponding assigned and unassigned event has the same reassignment_counter. This strictly increases with each unassign command for the same contract. Creation of the contract corresponds to reassignment_counter 0.
    */
    'reassignmentCounter': number;
    /**
    * The id of the unassigned contract 
    */
    'contractId': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "submitter",
            "baseName": "submitter",
            "type": "string",
            "format": ""
        },
        {
            "name": "sourceSynchronizer",
            "baseName": "source_synchronizer",
            "type": "string",
            "format": ""
        },
        {
            "name": "migrationId",
            "baseName": "migration_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "targetSynchronizer",
            "baseName": "target_synchronizer",
            "type": "string",
            "format": ""
        },
        {
            "name": "unassignId",
            "baseName": "unassign_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "reassignmentCounter",
            "baseName": "reassignment_counter",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "contractId",
            "baseName": "contract_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdateHistoryUnassignment.attributeTypeMap;
    }

    public constructor() {
    }
}
