/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CreatedEvent } from '../models/CreatedEvent';
import { HttpFile } from '../http/http';

export class UpdateHistoryAssignment {
    /**
    * The party ID who submitted this reassignment 
    */
    'submitter': string;
    /**
    * The id of the synchronizer from which the contract was reassigned 
    */
    'sourceSynchronizer': string;
    /**
    * The id of the synchronizer to which the contract was reassigned 
    */
    'targetSynchronizer': string;
    /**
    * The migration id of the target synchronizer 
    */
    'migrationId': number;
    /**
    * The id of the corresponding unassign event; this assignment will usually, but not always, occur after the so-identified unassignment event. 
    */
    'unassignId': string;
    'createdEvent': CreatedEvent;
    /**
    * Each corresponding assigned and unassigned event has the same reassignment_counter. This strictly increases with each unassign command for the same contract. Creation of the contract corresponds to reassignment_counter 0.
    */
    'reassignmentCounter': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "submitter",
            "baseName": "submitter",
            "type": "string",
            "format": ""
        },
        {
            "name": "sourceSynchronizer",
            "baseName": "source_synchronizer",
            "type": "string",
            "format": ""
        },
        {
            "name": "targetSynchronizer",
            "baseName": "target_synchronizer",
            "type": "string",
            "format": ""
        },
        {
            "name": "migrationId",
            "baseName": "migration_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "unassignId",
            "baseName": "unassign_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdEvent",
            "baseName": "created_event",
            "type": "CreatedEvent",
            "format": ""
        },
        {
            "name": "reassignmentCounter",
            "baseName": "reassignment_counter",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return UpdateHistoryAssignment.attributeTypeMap;
    }

    public constructor() {
    }
}
