/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UpdateHistoryAssignment } from '../models/UpdateHistoryAssignment';
import { UpdateHistoryUnassignment } from '../models/UpdateHistoryUnassignment';
import { HttpFile } from '../http/http';

/**
* The reassignment event. May be an assignment or unassignment. 
*/
/**
 * @type UpdateHistoryReassignmentEvent
 * Type
 * @export
 */
export type UpdateHistoryReassignmentEvent = UpdateHistoryAssignment | UpdateHistoryUnassignment;

/**
* @type UpdateHistoryReassignmentEventClass
    * The reassignment event. May be an assignment or unassignment. 
* @export
*/
export class UpdateHistoryReassignmentEventClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

