/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UpdateHistoryReassignmentEvent } from '../models/UpdateHistoryReassignmentEvent';
import { HttpFile } from '../http/http';

/**
* A contract reassignment between synchronizer. May be an assignment or unassignment.
*/
export class UpdateHistoryReassignment {
    /**
    * The id of the update. 
    */
    'updateId': string;
    /**
    * The absolute offset. Note that this field may not be the same across nodes, and therefore should not be compared between SVs. 
    */
    'offset': string;
    /**
    * The time at which the transaction was sequenced. 
    */
    'recordTime': string;
    'event': UpdateHistoryReassignmentEvent;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "updateId",
            "baseName": "update_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "offset",
            "baseName": "offset",
            "type": "string",
            "format": ""
        },
        {
            "name": "recordTime",
            "baseName": "record_time",
            "type": "string",
            "format": ""
        },
        {
            "name": "event",
            "baseName": "event",
            "type": "UpdateHistoryReassignmentEvent",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdateHistoryReassignment.attributeTypeMap;
    }

    public constructor() {
    }
}
