/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UpdateHistoryReassignment } from '../models/UpdateHistoryReassignment';
import { UpdateHistoryTransaction } from '../models/UpdateHistoryTransaction';
import { HttpFile } from '../http/http';

/**
* An individual item in the update history. May be a transaction or a contract reassignment. 
*/
/**
 * @type UpdateHistoryItem
 * Type
 * @export
 */
export type UpdateHistoryItem = UpdateHistoryReassignment | UpdateHistoryTransaction;

/**
* @type UpdateHistoryItemClass
    * An individual item in the update history. May be a transaction or a contract reassignment. 
* @export
*/
export class UpdateHistoryItemClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

