/**
 * Scan API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ValidatorPurchasedTraffic {
    'validator': string;
    'numPurchases': number;
    'totalTrafficPurchased': number;
    'totalCcSpent': string;
    'lastPurchasedInRound': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "validator",
            "baseName": "validator",
            "type": "string",
            "format": ""
        },
        {
            "name": "numPurchases",
            "baseName": "numPurchases",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "totalTrafficPurchased",
            "baseName": "totalTrafficPurchased",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "totalCcSpent",
            "baseName": "totalCcSpent",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastPurchasedInRound",
            "baseName": "lastPurchasedInRound",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return ValidatorPurchasedTraffic.attributeTypeMap;
    }

    public constructor() {
    }
}
